import { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    slug: 'porsche-911-gt3-2022',
    title: '2022 Porsche 911 GT3',
    status: 'live',
    make: 'Porsche',
    model: '911 GT3',
    variant: 'GT3 PDK',
    year: 2022,
    mileage: 3200,
    price: 189995,
    colour: 'GT Silver Metallic',
    bodyType: 'Coupe',
    transmission: 'PDK',
    fuelType: 'Petrol',
    engineSize: '4.0L Flat-Six',
    power: '510 bhp',
    sellerType: 'private',
    sellerName: 'Private Seller',
    location: 'London',
    featured: true,
    description:
      "An exceptional example of Porsche's most focused road car. Delivered new to the UK with full Porsche main dealer history. Fitted with the Weissach package, carbon-ceramic brakes and clubsport roll cage. One private owner from new, supplied with all books, manuals and two keys.",
    specs: [
      { label: 'Engine', value: '4.0L Naturally Aspirated Flat-Six' },
      { label: 'Power', value: '510 bhp' },
      { label: 'Torque', value: '470 Nm' },
      { label: '0–62 mph', value: '3.4 seconds' },
      { label: 'Top Speed', value: '198 mph' },
      { label: 'Transmission', value: '7-speed PDK' },
      { label: 'Drive', value: 'RWD' },
      { label: 'CO₂ Emissions', value: '249 g/km' },
    ],
  },
  {
    id: '2',
    slug: 'ferrari-roma-2021',
    title: '2021 Ferrari Roma',
    status: 'live',
    make: 'Ferrari',
    model: 'Roma',
    variant: 'V8 Turbo',
    year: 2021,
    mileage: 8100,
    price: 215000,
    colour: 'Rosso Portofino',
    bodyType: 'Coupe',
    transmission: '8-Speed DCT',
    fuelType: 'Petrol',
    engineSize: '3.9L Twin-Turbo V8',
    power: '612 bhp',
    sellerType: 'dealer',
    sellerName: 'Premier Collection Ltd',
    location: 'Surrey',
    featured: true,
    description:
      "The Roma represents a new chapter in Ferrari's GT lineage — a beautiful, effortlessly powerful grand tourer. This example presents in the stunning Rosso Portofino with a Creme interior. Ferrari Approved with the remaining factory warranty included. Delivered with full Ferrari dealer service history.",
    specs: [
      { label: 'Engine', value: '3.9L Twin-Turbocharged V8' },
      { label: 'Power', value: '612 bhp' },
      { label: 'Torque', value: '760 Nm' },
      { label: '0–62 mph', value: '3.4 seconds' },
      { label: 'Top Speed', value: '199 mph' },
      { label: 'Transmission', value: '8-speed DCT' },
      { label: 'Drive', value: 'RWD' },
      { label: 'CO₂ Emissions', value: '275 g/km' },
    ],
  },
  {
    id: '3',
    slug: 'aston-martin-db11-2023',
    title: '2023 Aston Martin DB11',
    status: 'live',
    make: 'Aston Martin',
    model: 'DB11',
    variant: 'V8 Coupe',
    year: 2023,
    mileage: 1850,
    price: 168500,
    colour: 'China Grey',
    bodyType: 'Coupe',
    transmission: '8-Speed Auto',
    fuelType: 'Petrol',
    engineSize: '4.0L Twin-Turbo V8',
    power: '510 bhp',
    sellerType: 'private',
    sellerName: 'Private Seller',
    location: 'Cheshire',
    featured: true,
    description:
      'Near-new DB11 V8 finished in the elegant China Grey over Obsidian Black leather. Loaded with factory options including the Premium Audio Pack, Exterior Carbon Pack and Sports Plus Seats. Supplied with full Aston Martin dealer history and remaining manufacturer warranty.',
    specs: [
      { label: 'Engine', value: '4.0L Twin-Turbocharged V8' },
      { label: 'Power', value: '510 bhp' },
      { label: 'Torque', value: '675 Nm' },
      { label: '0–62 mph', value: '3.9 seconds' },
      { label: 'Top Speed', value: '187 mph' },
      { label: 'Transmission', value: '8-speed automatic' },
      { label: 'Drive', value: 'RWD' },
      { label: 'CO₂ Emissions', value: '255 g/km' },
    ],
  },
  {
    id: '4',
    slug: 'bentley-continental-gt-2020',
    title: '2020 Bentley Continental GT',
    status: 'live',
    make: 'Bentley',
    model: 'Continental GT',
    variant: 'V8 Coupe',
    year: 2020,
    mileage: 18500,
    price: 142000,
    colour: 'Silver Storm',
    bodyType: 'Coupe',
    transmission: '8-Speed DCT',
    fuelType: 'Petrol',
    engineSize: '4.0L Twin-Turbo V8',
    power: '542 bhp',
    sellerType: 'dealer',
    sellerName: 'Meridian Prestige',
    location: 'London',
    featured: false,
    description:
      'A stunning third-generation Continental GT in Silver Storm Metallic with Burnt Oak hide. This car benefits from the City Specification and Touring Specification packs. Full Bentley main dealer service history throughout with no expense spared.',
    specs: [
      { label: 'Engine', value: '4.0L Twin-Turbocharged V8' },
      { label: 'Power', value: '542 bhp' },
      { label: 'Torque', value: '770 Nm' },
      { label: '0–62 mph', value: '4.0 seconds' },
      { label: 'Top Speed', value: '198 mph' },
      { label: 'Transmission', value: '8-speed DCT' },
      { label: 'Drive', value: 'AWD' },
      { label: 'CO₂ Emissions', value: '285 g/km' },
    ],
  },
  {
    id: '5',
    slug: 'lamborghini-urus-2022',
    title: '2022 Lamborghini Urus S',
    status: 'live',
    make: 'Lamborghini',
    model: 'Urus S',
    variant: 'S',
    year: 2022,
    mileage: 6200,
    price: 219000,
    colour: 'Nero Noctis',
    bodyType: 'SUV',
    transmission: '8-Speed Auto',
    fuelType: 'Petrol',
    engineSize: '4.0L Twin-Turbo V8',
    power: '657 bhp',
    sellerType: 'dealer',
    sellerName: 'Premier Collection Ltd',
    location: 'London',
    featured: false,
    description:
      'The Lamborghini Urus S in Nero Noctis gloss black over black Alcantara. Packed with the Q-Citura stitching, carbon exterior package, Bang & Olufsen Advanced sound system and Lamborghini Telemetry. A formidable machine presented in exceptional condition.',
    specs: [
      { label: 'Engine', value: '4.0L Twin-Turbocharged V8' },
      { label: 'Power', value: '657 bhp' },
      { label: 'Torque', value: '850 Nm' },
      { label: '0–62 mph', value: '3.5 seconds' },
      { label: 'Top Speed', value: '190 mph' },
      { label: 'Transmission', value: '8-speed automatic' },
      { label: 'Drive', value: 'AWD' },
      { label: 'CO₂ Emissions', value: '325 g/km' },
    ],
  },
  {
    id: '6',
    slug: 'mclaren-720s-2021',
    title: '2021 McLaren 720S',
    status: 'live',
    make: 'McLaren',
    model: '720S',
    variant: 'Performance',
    year: 2021,
    mileage: 11300,
    price: 249000,
    colour: 'Papaya Spark',
    bodyType: 'Coupe',
    transmission: '7-Speed SSG',
    fuelType: 'Petrol',
    engineSize: '4.0L Twin-Turbo V8',
    power: '720 bhp',
    sellerType: 'private',
    sellerName: 'Private Seller',
    location: 'Hampshire',
    featured: false,
    description:
      'An immaculate 720S Performance in the iconic Papaya Spark over Ultrafabrics interior. MSO Defined options include gloss visual carbon fibre exterior, Stealth Pack and bespoke orange brake callipers. Full McLaren dealer service history from new.',
    specs: [
      { label: 'Engine', value: '4.0L Twin-Turbocharged V8' },
      { label: 'Power', value: '720 bhp' },
      { label: 'Torque', value: '770 Nm' },
      { label: '0–62 mph', value: '2.9 seconds' },
      { label: 'Top Speed', value: '212 mph' },
      { label: 'Transmission', value: '7-speed SSG' },
      { label: 'Drive', value: 'RWD' },
      { label: 'CO₂ Emissions', value: '249 g/km' },
    ],
  },
];

export const featuredVehicles = vehicles.filter((v) => v.featured);
