import { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    slug: 'porsche-911-gt3-2022',
    make: 'Porsche',
    model: '911 GT3',
    variant: 'GT3 PDK',
    year: 2022,
    mileage: 3200,
    price: 189995,
    color: 'GT Silver Metallic',
    bodyType: 'Coupe',
    transmission: 'PDK',
    fuelType: 'Petrol',
    engineSize: '4.0L Flat-Six',
    power: '510 bhp',
    sellerType: 'private',
    sellerName: 'Private Seller',
    location: 'London',
    featured: true,
    description:
      'An exceptional example of Porsche\'s most focused road car. Delivered new to the UK with full Porsche main dealer history. Fitted with the Weissach package, carbon-ceramic brakes and clubsport roll cage. One private owner from new, supplied with all books, manuals and two keys.',
    specs: {
      Engine: '4.0L Naturally Aspirated Flat-Six',
      Power: '510 bhp',
      Torque: '470 Nm',
      '0–62 mph': '3.4 seconds',
      'Top Speed': '198 mph',
      Transmission: '7-speed PDK',
      Drive: 'RWD',
      'CO₂ Emissions': '249 g/km',
    },
    gradient: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 50%, #1a1a1a 100%)',
  },
  {
    id: '2',
    slug: 'ferrari-roma-2021',
    make: 'Ferrari',
    model: 'Roma',
    variant: 'V8 Turbo',
    year: 2021,
    mileage: 8100,
    price: 215000,
    color: 'Rosso Portofino',
    bodyType: 'GT Coupe',
    transmission: '8-Speed DCT',
    fuelType: 'Petrol',
    engineSize: '3.9L Twin-Turbo V8',
    power: '612 bhp',
    sellerType: 'dealer',
    sellerName: 'Premier Collection Ltd',
    location: 'Surrey',
    featured: true,
    description:
      'The Roma represents a new chapter in Ferrari\'s GT lineage — a beautiful, effortlessly powerful grand tourer. This example presents in the stunning Rosso Portofino with a Creme interior. Ferrari Approved with the remaining factory warranty included. Delivered with full Ferrari dealer service history.',
    specs: {
      Engine: '3.9L Twin-Turbocharged V8',
      Power: '612 bhp',
      Torque: '760 Nm',
      '0–62 mph': '3.4 seconds',
      'Top Speed': '199 mph',
      Transmission: '8-speed DCT',
      Drive: 'RWD',
      'CO₂ Emissions': '275 g/km',
    },
    gradient: 'linear-gradient(135deg, #2a1a1a 0%, #3d1f1f 50%, #2a1a1a 100%)',
  },
  {
    id: '3',
    slug: 'aston-martin-db11-2023',
    make: 'Aston Martin',
    model: 'DB11',
    variant: 'V8 Coupe',
    year: 2023,
    mileage: 1850,
    price: 168500,
    color: 'China Grey',
    bodyType: 'Grand Tourer',
    transmission: '8-Speed Auto',
    fuelType: 'Petrol',
    engineSize: '4.0L Twin-Turbo V8',
    power: '510 bhp',
    sellerType: 'private',
    sellerName: 'Private Seller',
    location: 'Cheshire',
    featured: true,
    description:
      'Near-new DB11 V8 finished in the elegant China Grey over Obsidian Black leather. Loaded with factory options including the Premium Audio Pack, Exterior Carbon Pack and Sports Plus Seats. Supplied with full Aston Martin dealer history and remaining manufacturer warranty.',
    specs: {
      Engine: '4.0L Twin-Turbocharged V8',
      Power: '510 bhp',
      Torque: '675 Nm',
      '0–62 mph': '3.9 seconds',
      'Top Speed': '187 mph',
      Transmission: '8-speed automatic',
      Drive: 'RWD',
      'CO₂ Emissions': '255 g/km',
    },
    gradient: 'linear-gradient(135deg, #1a1c1a 0%, #252b25 50%, #1a1c1a 100%)',
  },
  {
    id: '4',
    slug: 'bentley-continental-gt-2020',
    make: 'Bentley',
    model: 'Continental GT',
    variant: 'V8 Coupe',
    year: 2020,
    mileage: 18500,
    price: 142000,
    color: 'Silver Storm',
    bodyType: 'Grand Tourer',
    transmission: '8-Speed DCT',
    fuelType: 'Petrol',
    engineSize: '4.0L Twin-Turbo V8',
    power: '542 bhp',
    sellerType: 'dealer',
    sellerName: 'Meridian Prestige',
    location: 'London',
    featured: false,
    description:
      'A stunning third-generation Continental GT in Silver Storm Metallic with Burnt Oak hide. This car benefits from the City Specification and Touring Specification packs. Full Bentley main dealer service history throughout with no expense spared.',
    specs: {
      Engine: '4.0L Twin-Turbocharged V8',
      Power: '542 bhp',
      Torque: '770 Nm',
      '0–62 mph': '4.0 seconds',
      'Top Speed': '198 mph',
      Transmission: '8-speed DCT',
      Drive: 'AWD',
      'CO₂ Emissions': '285 g/km',
    },
    gradient: 'linear-gradient(135deg, #1c1c1c 0%, #2a2a2a 50%, #1c1c1c 100%)',
  },
  {
    id: '5',
    slug: 'lamborghini-urus-2022',
    make: 'Lamborghini',
    model: 'Urus S',
    variant: 'S',
    year: 2022,
    mileage: 6200,
    price: 219000,
    color: 'Nero Noctis',
    bodyType: 'SUV',
    transmission: '8-Speed Auto',
    fuelType: 'Petrol',
    engineSize: '4.0L Twin-Turbo V8',
    power: '657 bhp',
    sellerType: 'dealer',
    sellerName: 'Premier Collection Ltd',
    location: 'London',
    featured: false,
    description:
      'The Lamborghini Urus S in Nero Noctis gloss black over black Alcantara. Packed with the Q-Citura stitching, carbon exterior package, Bang & Olufsen Advanced sound system and Lamborghini Telemetry. A formidable machine presented in exceptional condition.',
    specs: {
      Engine: '4.0L Twin-Turbocharged V8',
      Power: '657 bhp',
      Torque: '850 Nm',
      '0–62 mph': '3.5 seconds',
      'Top Speed': '190 mph',
      Transmission: '8-speed automatic',
      Drive: 'AWD',
      'CO₂ Emissions': '325 g/km',
    },
    gradient: 'linear-gradient(135deg, #0f0f0f 0%, #1a1a1a 50%, #0f0f0f 100%)',
  },
  {
    id: '6',
    slug: 'mclaren-720s-2021',
    make: 'McLaren',
    model: '720S',
    variant: 'Performance',
    year: 2021,
    mileage: 11300,
    price: 249000,
    color: 'Papaya Spark',
    bodyType: 'Supercar',
    transmission: '7-Speed SSG',
    fuelType: 'Petrol',
    engineSize: '4.0L Twin-Turbo V8',
    power: '720 bhp',
    sellerType: 'private',
    sellerName: 'Private Seller',
    location: 'Hampshire',
    featured: false,
    description:
      'An immaculate 720S Performance in the iconic Papaya Spark over Ultrafabrics interior. MSO Defined options include gloss visual carbon fibre exterior, Stealth Pack and bespoke orange brake callipers. Full McLaren dealer service history from new.',
    specs: {
      Engine: '4.0L Twin-Turbocharged V8',
      Power: '720 bhp',
      Torque: '770 Nm',
      '0–62 mph': '2.9 seconds',
      'Top Speed': '212 mph',
      Transmission: '7-speed SSG',
      Drive: 'RWD',
      'CO₂ Emissions': '249 g/km',
    },
    gradient: 'linear-gradient(135deg, #1f1510 0%, #2e1e0e 50%, #1f1510 100%)',
  },
];

export const featuredVehicles = vehicles.filter((v) => v.featured);

export const makes = [...new Set(vehicles.map((v) => v.make))].sort();
export const bodyTypes = [...new Set(vehicles.map((v) => v.bodyType))].sort();
